// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NGRPrisonAPI.DataContext;

namespace NGRPrisonAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NGRPrisonAPI.Models.Inmate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Offenses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrisonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RelasedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentencedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrisonId");

                    b.HasIndex("StateId");

                    b.ToTable("Inmates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2020, 10, 24, 2, 24, 5, 7, DateTimeKind.Utc).AddTicks(4815),
                            DateOfBirth = new DateTime(1965, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            Gender = "Female",
                            LastName = "Doe",
                            Offenses = "Aggravated sex and armed robbery",
                            PrisonId = 1,
                            RelasedDate = new DateTime(2010, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SentencedDate = new DateTime(1995, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2020, 10, 24, 2, 24, 5, 7, DateTimeKind.Utc).AddTicks(5876),
                            DateOfBirth = new DateTime(1960, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            Gender = "Male",
                            LastName = "Doe",
                            Offenses = "Serial Rapist",
                            PrisonId = 3,
                            RelasedDate = new DateTime(2020, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SentencedDate = new DateTime(1990, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StateId = 2
                        });
                });

            modelBuilder.Entity("NGRPrisonAPI.Models.Prison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrisonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Prisons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2020, 10, 24, 2, 24, 5, 7, DateTimeKind.Utc).AddTicks(3719),
                            EstablishedDate = new DateTime(1990, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrisonName = "Abia Maximum",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2020, 10, 24, 2, 24, 5, 7, DateTimeKind.Utc).AddTicks(4603),
                            EstablishedDate = new DateTime(1980, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrisonName = "Abia Manimum",
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2020, 10, 24, 2, 24, 5, 7, DateTimeKind.Utc).AddTicks(4621),
                            EstablishedDate = new DateTime(1980, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrisonName = "Imo Maximum",
                            StateId = 2
                        });
                });

            modelBuilder.Entity("NGRPrisonAPI.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StateName = "Abia"
                        },
                        new
                        {
                            Id = 2,
                            StateName = "Imo"
                        });
                });

            modelBuilder.Entity("NGRPrisonAPI.Models.Inmate", b =>
                {
                    b.HasOne("NGRPrisonAPI.Models.Prison", "Prison")
                        .WithMany("Inmates")
                        .HasForeignKey("PrisonId");

                    b.HasOne("NGRPrisonAPI.Models.State", "State")
                        .WithMany("Inmates")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NGRPrisonAPI.Models.Prison", b =>
                {
                    b.HasOne("NGRPrisonAPI.Models.State", "State")
                        .WithMany("Prisons")
                        .HasForeignKey("StateId");
                });
#pragma warning restore 612, 618
        }
    }
}
